"""empty message

Revision ID: 029b394e3786
Revises: 1cd7919f6d2c
Create Date: 2024-05-17 16:30:11.311011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029b394e3786'
down_revision = '1cd7919f6d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('id_ad', sa.String(length=100), nullable=False),
    sa.Column('user_interested', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.drop_table('message')
    # ### end Alembic commands ###
