"""empty message

Revision ID: 1cf6447bb112
Revises: 
Create Date: 2024-05-10 03:17:19.020209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf6447bb112'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('ad',
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('ad_title', sa.String(length=100), nullable=False),
    sa.Column('game_type', sa.String(length=100), nullable=False),
    sa.Column('game_rank', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('skins', sa.Boolean(), nullable=False),
    sa.Column('exclusive', sa.Boolean(), nullable=False),
    sa.Column('Extra_Descrip', sa.String(), nullable=True),
    sa.Column('user_username', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('ad_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad')
    op.drop_table('user')
    # ### end Alembic commands ###
