"""empty message

Revision ID: 321549d9f1a4
Revises: 1cf6447bb112
Create Date: 2024-05-11 17:18:36.193607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321549d9f1a4'
down_revision = '1cf6447bb112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
