"""empty message

Revision ID: 74ac61169ec9
Revises: d39bb7155e4b
Create Date: 2024-05-19 14:01:54.388169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ac61169ec9'
down_revision = 'd39bb7155e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_folder', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_column('image_folder')

    # ### end Alembic commands ###
