"""empty message

Revision ID: 830e5e21c19c
Revises: 321549d9f1a4
Create Date: 2024-05-14 17:35:14.008061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830e5e21c19c'
down_revision = '321549d9f1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wishlist', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wishlist')

    # ### end Alembic commands ###
