"""empty message

Revision ID: d39bb7155e4b
Revises: fe0c68377da4
Create Date: 2024-05-19 00:35:41.881193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39bb7155e4b'
down_revision = 'fe0c68377da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_rankid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_column('_rankid')

    # ### end Alembic commands ###
