"""Initial migration.

Revision ID: e081f7409ced
Revises: 
Create Date: 2024-05-07 17:27:44.873635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e081f7409ced'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('ad',
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('ad_title', sa.String(length=100), nullable=False),
    sa.Column('user_username', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('ad_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad')
    op.drop_table('user')
    # ### end Alembic commands ###
