"""added image_folder to ad model

Revision ID: e7515b487d8c
Revises: fe0c68377da4
Create Date: 2024-05-18 18:49:30.256060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7515b487d8c'
down_revision = 'fe0c68377da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_folder', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_column('image_folder')

    # ### end Alembic commands ###
